[project]
name = "dbt-snowflake-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.11.4",
    "dbt-snowflake>=1.11.1",
    "requests>=2.32.5",
]
